### ISSUE TITLE
Error: window.AssistantHost is not ready. The ready method has the type "undefined"

### ISSUE THREAD

**Issue by azeek21** [salute-developers/salutejs-client#154]
I think this has happened before, I couldn't solve this for some time. Everything working fine with createSmartappDebugger on dev mode.  Related: #80 #81

Here's a screenshot. I am using latest NextJs and doing an [export](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports), no ssr of any kind.
![image](https://github.com/salute-developers/salutejs-client/assets/91887882/6bcc5194-479b-479f-bb67-03508e132b7f)

I tried to bum up the timeout to 1 second and retry counts to 10 and even after 10 seconds it doesn't seem to work.
![noready](https://github.com/salute-developers/salutejs-client/assets/91887882/e4733623-da68-4f2e-93ef-e86efff5756e)

**Comment by sasha-tlt** [comment]
Hi! It`s a expected behavior. You are making a canvas app and you must start it on a device or on a app (salute, sbol) on android/ios. The dev-mode (`createSmartAppDebugger`) emulates a device (or app), the prod-mode expects a device (or app) environment
