### ISSUE TITLE
Ошибка после обновления @salutejs/client до версии 1.33.3

### ISSUE THREAD

**Issue by DarkSharkk** [salute-developers/salutejs-client#211]
Обновился с 1.32.5 до 1.33.3.
Поймал такую ошибку в файле sentry.client.config: TypeError: Cannot destructure property 'params' of 'window.config' as it is undefined.
После обхода этой ошибки или при попытке ловлю такую в node_modules/@salutejs/client/dist/assistant-edbce: ReferenceError: self is not defined.
До обновляения всё работало.

**Comment by soulko** [comment]
https://github.com/salute-developers/salutejs-client/pull/213
